)CM  PACKAGE SHIPMENT BATCH JCL -  NETVIEW FTP TRANSFERS - ISPSLIB(C1BMXFTP)
)CM
)CM  THIS IS THE SECOND STEP IN THE FTP TRANSMISSION PROCESS.  JCL
)CM  GENERATED BY THE SHIPMENT STAGING UTILITY WILL CAUSE THE TRANSFER
)CM  OF THE STAGING DATASETS AND THE ARJOB TO EXECUTE.
)CM
)CM  * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
)CM
)CM  TAILORING INSTRUCTIONS:
)CM
)CM  ADJUST THE SYSUT2 INTERNAL READER PARAMETERS, IF NECESSARY.
)CM
)CM
)CM  * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
)CM
//* *============================================* ISPSLIB(C1BMXFTP) *
//* *==============================================================* *
//* *==============================================================* *
//* *==============================================================* *
//* *==============================================================* *
//*
//&VNBXSTP EXEC PGM=IEBGENER,COND=(12,LE,NDVRSHIP)
//SYSUT1    DD DSN=&&&&XFTC,DISP=(OLD,PASS)
//SYSUT2    DD SYSOUT=(A,INTRDR)
//SYSPRINT  DD SYSOUT=*
//SYSIN     DD DUMMY
