 SIGNON
 SUBMIT  PROC=WNS2FFJX SNODE=<SNODE> -
   NEWNAME=<NEWNAME> -
   MAXDELAY=00:15:00 -
   &FILEIN1=PGDF.NBINDOH.BINDS -
   &FILEOUT1='<L>:\BINDS\PASSWORD.TXT' -
   &FILEIN2=<BINDFILE> -
   &FILEOUT2='<L>:\BINDS\BIND.SQL' -
   &WNCMD01=|| -
    'PGM(<L>:\BINDS\BINDOH.BAT) ARGS(<D> <SY> <CMR> <I>) DESKTOP(YES)' -
   &CA7JOBI=<NEWNAME>
 SIGNOFF
