 ADD ELEMENT &CHANGE
 FROM DSNAME '&WIZLIB' MEMBER &C1TYPE
 TO ENVIRONMENT &C1ENV SYSTEM &C1SYSTEM SUBSYSTEM &C1SYSTEM.1
 TYPE &C1TYPE
 OPTIONS
 CCID &CHANGE
 COMMENTS '#'
 UPDATE
 PROCESSOR GROUP &PROCGRP &OVER
 .
