 MOVE ELEMENT &CHANGE
 FROM ENVIRONMENT &C1ENV SYSTEM &C1SYSTEM SUBSYSTEM &C1SYSTEM.1
 TYPE &C1TYPE
)SEL &C1ENV = ACPT
 STAGE NUMBER 2
)ENDSEL
)SEL &C1ENV = PROD
 STAGE NUMBER 1
)ENDSEL
 OPTIONS
 CCID &CHANGE
 COMMENTS '#'
 .
