)CM  PACKAGE SHIPMENT BATCH JCL -  BDT USING JES - ISPSLIB(C1BMXBD1)
)CM
)CM  THIS SKELETON IS USED TO SUBMIT BDT TRANSMISSION JCL GENERATED BY
)CM  THE PACKAGE SHIPMENT UTILITY TO THE INTERNAL READER VIA IEBGENER.
)CM
)CM  * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
)CM
)CM  TAILORING INSTRUCTIONS:
)CM
)CM  ADJUST THE SYSUT2 INTERNAL READER PARAMETERS, IF NECESSARY.
)CM
)CM  * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
)CM
//* *============================================* ISPSLIB(C1BMXBD1) *
//* *==============================================================* *
//* *==============================================================* *
//* *==============================================================* *
//* *==============================================================* *
//&VNBXSTP EXEC PGM=IEBGENER,COND=(12,LE,NDVRSHIP)
//SYSUT1    DD DSN=&&&&XB1C,DISP=(OLD,PASS)
//SYSUT2    DD SYSOUT=(A,INTRDR)
//SYSPRINT  DD SYSOUT=*
//SYSIN     DD DUMMY
