  DEFINE PROC GRO "<PRCGRP>"
      TO SYSTEM   "<SYSTEM>"
         TYPE     "<TYPE>  "
         ENVIRON  "<ENV>   "
         STAGE ID "X"
      DESCRIPTION "<DESC UP TO 50 CHARACTERS>...                     "
)N
)N    GENERATE PROCESSOR NAME <GENPRC> DO NOT ALLOW FOREGROUND EXE
)N    MOVE     PROCESSOR NAME <MOVPRC> DO NOT ALLOW FOREGROUND EXE
)N    DELETE   PROCESSOR NAME <DELPRC> DO NOT ALLOW FOREGROUND EXE
)N
)N    MOVE     ACTION USES GENERATE PROCESSOR
)N    TRANSFER ACTION USES MOVE     PROCESSOR
)N
)N    NEXT PROCESSOR GROUP <PRCGRP>
)N    PROCESSOR OUTPUT TYPE "<TYPENM><PROGRP>"
  .
