  DEFINE SYSTEM   "<SYSTEM>"
      TO ENVIRON  "<ENV>   "
      DESCRIPTION "<DESC UP TO 50 CHARACTERS>...                     "
)N
)N    COMMENTS    REQUIRED
)N    CCID        REQUIRED
)N
)N    NEXT SYSTEM "<SYSTEM>"
)N    DUPLICATE ELEMENT NAME CHECK IS ACTIVE
)N       ERROR SEVERITY LEVEL IS W|E|C
)N    DUPLICATE PROCESSOR OUTPUT TYPE CHECK IS ACTIVE
)N       ACROSS SUBSYSTEMS
)N          ERROR SEVERITY LEVEL IS W|E|C
)N    ELEMENT JUMP ACKNOWLEDGEMENT NOT REQUIRED
)N    SIGNOUT IS ACTIVE
)N    SIGNOUT DATASET VALIDATION IS ACTIVE
)N    STAGE ONE LOAD LIBRARY IS "UPRFX.UQUAL.STG1.PRCSLOAD"
)N    STAGE ONE LIST LIBRARY IS "UPRFX.UQUAL.STG1.PRCSLIST"
)N    STAGE TWO LOAD LIBRARY IS "UPRFX.UQUAL.STG2.PRCSLOAD"
)N    STAGE TWO LIST LIBRARY IS "UPRFX.UQUAL.STG2.PRCSLIST"
)N    RETAIN ELEMENT LEVEL FOR NNN MONTHS
)N    RETAIN COMPONENT LEVEL FOR NNN MONTHS
  .
