  DEFINE SUBSYS   "<SUBSYS>"
      TO ENVIRON  "<ENV>   "
         SYSTEM   "<SYSTEM>"
      DESCRIPTION "<DESC UP TO 50 CHARACTERS>...                     "
)N
)N    NEXT SUBSYS "<SUBSYS>"
)N    EXCLUDE DUPLICATE PROCESSOR OUTPUT CHECK
  .
