 SET OPTION
)N
)N USE "MD" LINE COMMAND TO PICK VALID OPTIONS FROM BELOW...
)N
)N AUTOGEN
)N   SPAN NONE
)N   SPAN ALL
)N   SPAN SYSTEMS
)N   SPAN SUBSYSTEMS
)N
)N BYPASS DELETE PROCESSOR
)N BYPASS DUPLICATE OUTPUT CHECK
)N BYPASS ELEMENT DELETE
)N BYPASS GENERATE PROCESSOR
)N PROCESSOR GROUP EQ "      "
)N
)N CCID "            "
)N COMMENT "                                        "
)N
)N COMPONENT
)N   BROWSE
)N   CHANGE
)N   HISTORY
)N   SUMMARY
)N COMPONENT VALIDATION
)N
)N COPYBACK
)N NOSOURCE
)N DELETE INPUT SOURCE
)N DETAIL REPORT
)N
)N ELEMENT
)N   BROWSE
)N   CHANGE
)N   HISTORY
)N   SUMMARY
)N   LISTING
)N
)N EXPAND INCLUDES
)N IGNORE GENERATE FAILED
)N NEW VERSION  "VV"
)N NO SIGNOUT
)N NOCC
)N ONLY COMPONENT
)N OVERRIDE SIGNOUT
)N REPLACE MEMBER
)N RETAIN GENERATE HISTORY
)N RETAIN SIGNOUT
)N
)N SIGNIN
)N SIGNOUT TO  "USERID  "
)N SEARCH
)N   ALL
)N   FIRST FOUND
)N NOSEARCH
)N SHOW TEXT
)N   PLUS N LINES
)N SYNCHRONIZATION
)N SYNCHRONIZE
)N TERSE
)N   MESSAGES
)N UPDATE IF PRESENT
)N WITH HISTORY
 .
