   BACKOUT  PACKAGE <PKGID>
)N        STATEMENT <NUMBER> ELEMENT "<ELEMENT>"
)N
)N NOTE: THE STATEMENT NUMBER/ELEMENT CLAUSE IS OPTIONAL
)N       THE DEFAULT BEING TO BACKOUT THE ENTIRE PACKAGE.
)N       IF YOU WANT TO BACKOUT MORE THAN ONE ELEMENT
)N       REPEAT THE ENTIRE CLAUSE.
   .
