)N DELETE SYSTEM       "<SYSTEM>"
)N    FROM ENVIRONMENT "<ENV>   ".
)N
)N DELETE  SUBSYSTEM   "<SUBSYS>"
)N    FROM ENVIRONMENT "<ENV>   "
)N         SYSTEM      "<SYSTEM>".
)N
)N DELETE  TYPE        "<TYPE>  "
)N    FROM ENVIRONMENT "<ENV>   "
)N         SYSTEM      "<SYSTEM>"
)N         STAGE ID    "X".
)N
)N DELETE  PROCESSOR GROUP "<GRPNAM>"
)N    FROM ENVIRONMENT "<ENV>   "
)N         SYSTEM      "<SYSTEM>"
)N         TYPE        "<TYPE>  "
)N         STAGE ID    "X".
)N
)N
)N DELETE  PROCESSOR SYMBOL
)N    FROM ENVIRONMENT "<ENV>   "
)N         SYSTEM      "<SYSTEM>"
)N         TYPE        "<TYPE>  "
)N         STAGE ID    "X"
)N         PROCESSOR GROUP "<GRPNAM>"
)N         PROCESSOR TYPE GENERATE|MOVE|DELETE
)N       SYMBOL EQ <SYM1>
)N       SYMBOL EQ <SYM2>
)N    .
)N
)N THE DELETE SCL CAN BE USED TO DELETE OBJECTS ONLY WHERE NO
)N SUBORDINATES OR ELEMENTS EXIST. USE MD (MAKEDATA) LINE COMMANDS
)N TO BUILD SCL FOR THE OBJECT TYPES YOU WANT TO DELETE.
)N SEE THE SCL GUIDE FOR THE FULL SYNTAX OR TO DELETE OTHER
)N OBJECT TYPES.
