   BUILD SCL FOR ENVIRONMENT "ENV*"
)N            TO DDNAME "<DDNAME>"
              TO DSNAME "<DSNAME>"
                 MEMBER "<MEMBER>"
)N                    REPLACE
   .
)N
)N THE BUILD SCL FOR ENVIRONMENT <MASK> WILL BUILD ALL THE DEFINE
)N SCL FOR ALL SYSTEMS, SUBSYSTEMS, TYPES ETC. IF THE ENVIRONMENT
)N NAME IS A MASK IT CAN MATCH MULTIPLE ENVIRONMENTS.
)N
)N NOTE: IF YOU ONLY REQUIRE SYSTEM, OR TYPE INFORMATION ADJUST THE
)N       SCL TO REQUEST FROM SYS/TYPE... AND ADD A FROM ENV... CLAUSE
