  DEFINE TYPE     "<TYPE>  "
      TO SYSTEM   "<SYSTEM>"
         ENVIRON  "<ENV>   "
         STAGE ID "X"
      DESCRIPTION "<DESC UP TO 50 CHARACTERS>...                     "
)N
)N    SOURCE ELEMENT LENGTH NN
)N    COMPARE FROM COLUMN FF TO TT
)N    DATA FORMAT IS TEXT|BINARY
)N    ELEMENT RECFM IS FIXED|VARIABLE|NOT DEFINED
)N    USS RECFM IS NL|F|CR|CRLF|LF|COMP|V
)N    LANGUAGE IS DATA|COBOL|ASM|...
)N    PANVALET  LANGUAGE IS LANGUAGE-NAME
)N    LIBRARIAN LANGUAGE IS LANGUAGE-NAME
)N
)N    BASE LIBRARY          "PR.&C1SY..&C1SU..&C1EN(1,3)&C1S#..&C1TY"
)N    DELTA LIBRARY         "PR.&C1SY..&C1SU..&C1EN(1,3)&C1S#..DELTA"
)N    INCLUDE LIBRARY       "PR.&C1SY..&C1SU..&C1EN(1,3)&C1S#..INCLUDE"
)N    SOURCE OUTPUT LIBRARY "PR.&C1SY..&C1SU..&C1EN(1,3)&C1S#..OUTPUT"
)N
)N    NEXT TYPE   "<TYPE>  "
)N    EXPAND INCLUDES
)N    DEFAULT PROCESSOR GROUP *NOPROC*
)N    ELEMENT DELTA FORMAT REVERSE|FORWARD|IMAGE|LOG
)N    COMPRESS BASE
)N    REGRESSION PERCENTAGE THRESHOLD IS NN
)N    REGRESSION SEVERITY IS CAUTION|INFO|WARNING|ERROR
)N    DO NOT CONSOLIDATE ELEMENT LEVELS
)N    CONSOLIDATE ELEMENT AT LEVELS VV
)N      NUMBER OF ELEMENT LEVELS TO CONSOLIDATE LL
)N
)N    CONSOLIDATE COMPONENT LEVELS
)N    COMPONENT DELTA FORMAT IS FORWARD|REVERSE
)N    CONSOLIDATE COMPONENT AT LEVEL VV
)N    NUMBER OF COMPONENT LEVELS TO CONSOLIDATE LL
  .
