   EXECUTE  PACKAGE <PKGID>
)N   OPTION
)N       WHERE PACKAGE STATUS IS APPROVED OR EXECFAILED
)N       EXECUTION WINDOW
)N                 FROM   DDMMMYY HH:MM
)N                 TO     DDMMMYY HHH:MM
   .
)N
)N SUBMIT   PACKAGE <PKGID>
)N    JOBCARD
)N       DDNAME JCLIN
)N       DSNAME "<JOBCARD.DSNAME>" MEMBER "<MEM>"
)N    TO INTERNAL READER DDNAME JCLOUT
)N
)N    OPTION
)N       WHERE PACKAGE STATUS IS APPROVED OR EXECFAILED
)N       MULTIPLE JOBSTREAMS
)N          INCREMENT JOBNAME
)N          DO NOT INCREMENT JOBNAME
)N       JCL PROCEDURE NAME IS <PROCNAME>
)N .
)N
)N NOTE: YOU CAN EXECUTE A PACKAGE IN THE CURRENT JOBSTEP OR
)N   SUBMIT MATCHING PACKAGE(S) TO BE PROCESSED IN ANOTHER
)N       STREAM.  COMMENT/UNCOMMENT THE SYNTAX YOU REQUIRE
