 TRANSFER ELEMENT "        "
)N  VERSION VV LEVEL LL
     FROM ENV     "        " STAGE NUM " "
          SYS     "        " SUBSYSTEM "        " TYPE "        "
       TO ENV     "        " STAGE NUM " "
          SYS     "        " SUBSYSTEM "        " TYPE "        "
          ELEMENT "        "
)N
)N USE "MD" LINE COMMANDS TO CONVERT REQUIRED OPTIONS TO VALID SCL
)N NOTE: WHERE KEYWORDS ARE GROUPED, PICK ONE LINE ONLY E.G. SIGNOUT
)N
)N  OPTION
)N    CCID    "            "
)N    COMMENT "                                        "
)N    NEW VERSION <VV>
)N    IGNORE GENERATE FAILED
)N    OVERRIDE SIGNOUT
)N    WITH HISTORY
)N    SYNCHRONIZE
)N    BYPASS DUPLICATE OUTPUT CHECK
)N
)N      BYPASS GENERATE PROCESSOR
)N      PROCESSOR GROUP EQ <GROUP-NAME>
)N
)N      BYPASS ELEMENT DELETE
)N      BYPASS DELETE PROCESSOR
)N
)N      SIGNIN
)N      RETAIN SIGNOUT
)N      SIGNOUT TO <USERID>
)N
)N  WHERE
)N    CCID
)N      OF CURRENT  EQUAL <CCID>
)N      OF ALL      EQ   (<CCID1>, <CCID2>, <CCID3>)
)N      OF RETRIEVE =     <CCID>
)N      EQUAL <CCID>
)N
)N IF YOU NEED TO SELECT ELEMENTS IDENTIFIED UNDER MORE THAN ONE CCID,
)N YOU CAN SPECIFY MULTIPLE CCIDS BY ENCLOSING THE CCIDS WITH
)N PARENTHESES AND SEPARATING THEM WITH COMMAS.
)N THE CCIDS MAY EXTEND OVER MULTIPLE LINES IF NECESSARY.
)N
)N EXAMPLE 1: WHERE CCID OF CURRENT (PROJ__1, PROJ__2, PROJ__4)
)N EXAMPLE 2: WHERE CCID OF ALL (PROJ___)
)N
    .
